apiVersion: v1
kind: Pod
metadata:
  name: haproxy
  namespace: kube-system
spec:
  containers:
  - image: haproxytech/haproxy-alpine:2.4
    name: haproxy
    ports:
      - name: http
        containerPort: 80
        hostPort: 80
      - name: https
        containerPort: 443
        hostPort: 443
      - name: httpalt
        containerPort: 9090
        hostPort: 9090
      - name: kubeapi
        containerPort: {{cpn_api_ha_port}}
        hostPort: {{cpn_api_ha_port}}
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: localhost
        path: /healthz
        port: {{cpn_api_port}}
        scheme: HTTPS
    volumeMounts:
    - mountPath: /usr/local/etc/haproxy/haproxy.cfg
      name: haproxyconf
      readOnly: true
  hostNetwork: true
  resources:
    limits:
      memory: "128Mi"
  volumes:
  - hostPath:
      path: /etc/haproxy/haproxy.cfg
      type: FileOrCreate
    name: haproxyconf
status: {}
