apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: keepalived
  namespace: kube-system
spec:
  containers:
  - image: osixia/keepalived:2.0.20
    name: keepalived
    args:
      - --copy-service
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_BROADCAST
        - NET_RAW
    volumeMounts:
    - mountPath: /container/service/keepalived/assets/keepalived.conf
      name: config
      readOnly: True
    - mountPath: /etc/keepalived/check_kubeapi.sh
      name: check
      readOnly: True
  hostNetwork: true
  resources:
    limits:
      memory: "128Mi"
  volumes:
  - hostPath:
      path: /etc/keepalived/keepalived.cfg
    name: config
  - hostPath:
      path: /etc/keepalived/check_kubeapi.sh
    name: check
status: {}
